import { DEFAULT_TEXT_AI_MODEL } from "./config.js";
import { runTextClassification } from "./provider.js";
import { normalizeLabel, pickTopMatch, toPercent } from "./utils.js";

const AI_TEXT_LABELS = new Set([
    "chatgpt",
    "ai",
    "generated",
    "machine",
    "llm",
    "gpt",
    "synthetic",
]);
const HUMAN_TEXT_LABELS = new Set(["human", "real", "authentic", "organic", "written_by_human"]);

export const CURRENT_TEXT_AI_MODELS = [DEFAULT_TEXT_AI_MODEL];

export const summarizeAiGeneratedText = (predictions) => {
    const aiMatch = pickTopMatch(
        predictions,
        (label) =>
            AI_TEXT_LABELS.has(label) ||
            label.includes("chatgpt") ||
            label.includes("generated") ||
            label.includes("machine") ||
            label.includes("gpt") ||
            label.includes("ai"),
    );

    const humanMatch = pickTopMatch(
        predictions,
        (label) =>
            HUMAN_TEXT_LABELS.has(label) ||
            label.includes("human") ||
            label.includes("authentic") ||
            label.includes("organic"),
    );

    const fallbackTopPrediction = predictions[0] || null;
    const derivedAiScore =
        aiMatch?.score ??
        (fallbackTopPrediction && AI_TEXT_LABELS.has(normalizeLabel(fallbackTopPrediction.label))
            ? fallbackTopPrediction.score
            : null);
    const derivedHumanScore =
        humanMatch?.score ??
        (fallbackTopPrediction && HUMAN_TEXT_LABELS.has(normalizeLabel(fallbackTopPrediction.label))
            ? fallbackTopPrediction.score
            : null);
    const aiScore =
        derivedAiScore ??
        (typeof derivedHumanScore === "number" ? Math.max(0, 1 - derivedHumanScore) : 0);
    const humanScore =
        derivedHumanScore ??
        (typeof derivedAiScore === "number"
            ? Math.max(0, 1 - derivedAiScore)
            : Math.max(0, 1 - aiScore));

    return {
        topPrediction: fallbackTopPrediction,
        aiScore,
        aiPercent: toPercent(aiScore),
        humanScore,
        humanPercent: toPercent(humanScore),
        flagged: aiScore >= 0.6,
        status: aiScore >= 0.8 ? "likely_ai" : aiScore >= 0.6 ? "possible_ai" : "likely_real",
    };
};

export const summarizeOverallTextAiResult = (summary) => {
    if (summary.status === "likely_ai") {
        return {
            status: "likely_ai",
            label: "Likely AI-generated",
            message: "The detector strongly suggests this text was generated by AI.",
        };
    }

    if (summary.status === "possible_ai") {
        return {
            status: "possible_ai",
            label: "Possibly AI-generated",
            message: "The detector found moderate signs that this text may be AI-generated.",
        };
    }

    return {
        status: "likely_real",
        label: "Likely human-written",
        message: "The detector found stronger signs of human-written text than AI-generated text.",
    };
};

export async function analyzeTextContent({ text }) {
    const predictions = await runTextClassification({
        text,
        model: DEFAULT_TEXT_AI_MODEL,
    });
    const summary = summarizeAiGeneratedText(predictions);

    return {
        checkedAt: new Date().toISOString(),
        models: {
            aiGeneratedText: DEFAULT_TEXT_AI_MODEL,
        },
        overall: summarizeOverallTextAiResult(summary),
        aiGeneratedText: {
            predictions: predictions.map((prediction) => ({
                label: prediction.label,
                score: prediction.score,
                percent: toPercent(prediction.score),
            })),
            summary,
        },
    };
}
